### ISSUE TITLE
Enable custom root CA case 1 - python-based components

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku#2294]
In order to support custom root CA signed certificate in python-based components we need to:

1. Create a ConfigMap (main renku helm-charts) to store the provided certificate. The users would define a Renku global variable containing the certificate, in `global.clientCertificate.value` (this variable is already used by the KG).

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-pemstore
  namespace: renku
data:
  ca-cert.pem: |-
    -----BEGIN CERTIFICATE-----
    ASDF......
    -----END CERTIFICATE-----
```

2. Include the certificate in the `REQUESTS_CA_BUNDLE` environment variable. This value can be mounted from the ConfigMap previously defined.

```    
spec:
      containers:
      - name: <CONT_NAME>
        env:
        - name: REQUESTS_CA_BUNDLE
          value: /etc/ssl/certs/ca-cert.pem
        - name: SSL_CERT_FILE
          value: /etc/ssl/certs/ca-cert.pem
        volumeMounts:
        - name: ca-pemstore
          mountPath: /etc/ssl/certs/ca-cert.pem
          subPath: ca-cert.pem
          readOnly: true
```

A -non extensive- list of containers that should include this is:

```
renku-core core-datasets-workers
renku-core core-management-workers
renku-core core-scheduler
renku-core core
renku-gateway gateway
renku-gateway-auth gateway
renku-event-log event-log
hub hub
proxy chp
renku-notebooks notebooks
renku-ui ui
```

Please check for newly defined containers notably renku-core, renku-ui and renku-notebooks (Amalthea).

Reference: https://stackoverflow.com/a/43935319
