### ISSUE TITLE
Taging all the init images  

### ISSUE THREAD

**Issue by JGodin-C2C** [SwissDataScienceCenter/renku#3784]
**Latest used in init images tags**

Hello all ! 
I wanted to bring to your attention the fact that the init images are by default using the latest tag. 
I dont think this is a good idea as sometimes latest is 3 year old. 
For exemple 
https://hub.docker.com/r/renku/init-realm/tags?name=latest
While sometimes they simple does not exists 
https://hub.docker.com/r/renku/init-db/tags?name=latest

This forces us to inject those values. 

**Expected behavior**
A sane tag is used to identify the init images 

**Screenshots and/or execution output**
At the moment , i already found these values that are setted to latest : 

https://github.com/SwissDataScienceCenter/renku/blob/master/helm-chart/renku/values.yaml#L322
https://github.com/SwissDataScienceCenter/renku/blob/master/helm-chart/renku/values.yaml#L1589
https://github.com/SwissDataScienceCenter/renku/blob/master/helm-chart/renku/values.yaml#L1594

Regards 
J\x00

**Comment by olevski** [comment]
@JGodin-C2C these are updated by chartpress when we publish our helm charts. So if you look at any published helm chart you will see that the default values in the values file are specific tags that match the renku release. Not `latest`.

For example if you download 0.57.0 from here: 
https://github.com/SwissDataScienceCenter/helm-charts/blob/gh-pages/renku-0.57.0.tgz

And extract the contents and check the values file you will see:

```
...
## keycloak admin username/password is supplied.
  initRealm:
    image:
      repository: renku/init-realm
      tag: "0.57.0"
...
## The image used in startup scripts to initialize different postgress databases
initDb:
  image:
    repository: renku/init-db
    tag: "0.57.0"
## The image used for general platform initialization
platformInit:
  image:
    repository: renku/platform-init
    tag: "0.57.0"
...
```

The only time the "latest" versions would be used is if someone tries to deploy renku from the helm chart code in the renku repo - and not from a published version. Anyhow we can publish the "latest" images so that things work even in this case. If we wanted to tag these with a specific version we would have a bit of a problem because at the time of tagging the images would not be around. I.e. if we tagged these to 0.60.0 before 0.60.0 is released then the 0.60.0 images would not be around. And I would rather not complicate things to have to tag right after every release is done or to have a step in the release process that just builds the images and then stops and waits for us to upgrade the values file and then we continue with the helm chart publishing. Chartpress fixes exactly this problem and will always set the values in the values file to the right version. But to be safe we can also publish "latest" on every release.
