### ISSUE TITLE
missing credentials in test init container

### ISSUE THREAD

**Issue by fgeorgatos** [SwissDataScienceCenter/renku#398]
currently: 
```
renku-test                                   0/1       Init:Error   0          6m
```

2 fix:

* we need something to make tests easy to run helm from the command line, something like:
```
time helm --set KEYCLOAK_ADMIN_PASSWORD=bla GITLAB_SUDO_TOKEN=blabla helm test renku
```
(the above doesn't work, just to get the idea; i.e. to avoid re-editing `test-renku.yaml`)

**Comment by leafty** [comment]
@fgeorgatos The test pod template is missing some env var parameters, see: https://github.com/SwissDataScienceCenter/renku/blob/master/charts/renku/templates/tests/test-renku.yaml#L11-L15

The admin user/pass for keycloak is baked in the container so we need a way to change them in the template.

**Comment by rokroskar** [comment]
can't we inject `keycloak.keycloak.username` and `keycloak.keycloak.password`?

**Comment by leafty** [comment]
Not directly, but yaml refs can be used to not duplicate them.

**Comment by rokroskar** [comment]
something like this wouldn't work? 

```
      - name: KEYCLOAK_ADMIN_USER
        value: {{ .Values.keycloak.keycloak.user }}
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: {{ template "renku.fullname" . }}
            key: keycloak-password
```
